"""Photometry constants and flag names."""

from __future__ import annotations

ARCSEC2_TO_SR = 1.0 / (206265.0**2)
MJY_SR_TO_UJY_SR = 1.0e12

FLAG_CALIBRATION_MISSING = "CALIBRATION_MISSING"
FLAG_CALIBRATION_VERSION_MISMATCH = "CALIBRATION_VERSION_MISMATCH"
FLAG_SAPM_INVALID = "SAPM_INVALID"
FLAG_PSF_MISSING = "PSF_MISSING"
FLAG_PSF_TRUNCATED = "PSF_TRUNCATED"
FLAG_INSUFFICIENT_VALID_PIXELS = "INSUFFICIENT_VALID_PIXELS"
FLAG_BACKGROUND_POOR = "BACKGROUND_POOR"
FLAG_FIT_ERROR = "FIT_ERROR"
FLAG_FIT_ILL_CONDITIONED = "FIT_ILL_CONDITIONED"
FLAG_DEBLEND_UNSTABLE = "DEBLEND_UNSTABLE"
FLAG_CONTAMINATION_RISK = "CONTAMINATION_RISK"
FLAG_SEVERE_IMAGE_FLAG = "SEVERE_IMAGE_FLAG"
FLAG_EDGE_OF_CUTOUT = "EDGE_OF_CUTOUT"
FLAG_NEGATIVE_FORCED_FLUX = "NEGATIVE_FORCED_FLUX"
FLAG_NON_DETECTION = "NON_DETECTION"
FLAG_DETECTOR_COORD_FALLBACK = "DETECTOR_COORD_FALLBACK"
FLAG_TARGET_CORE_MASKED = "TARGET_CORE_MASKED"
FLAG_LOW_TEMPLATE_SUPPORT = "LOW_TEMPLATE_SUPPORT"
FLAG_CENTRAL_POSITIVE_RESIDUAL_AFTER_NEGATIVE_MODEL = "CENTRAL_POSITIVE_RESIDUAL_AFTER_NEGATIVE_MODEL"
FLAG_PSF_COORDINATE_UNCERTAIN = "PSF_COORDINATE_UNCERTAIN"
FLAG_PSF_RENDERING_INVALID = "PSF_RENDERING_INVALID"
FLAG_TARGET_POSSIBLY_EXTENDED = "TARGET_POSSIBLY_EXTENDED"
FLAG_TARGET_PSF_MISMATCH = "TARGET_PSF_MISMATCH"
FLAG_BACKGROUND_IMAGE_CLIPPED_FALLBACK = "BACKGROUND_IMAGE_CLIPPED_FALLBACK"
FLAG_BACKGROUND_2D_FALLBACK_CONSTANT = "BACKGROUND_2D_FALLBACK_CONSTANT"
FLAG_BACKGROUND_2D_UNSTABLE = "BACKGROUND_2D_UNSTABLE"
FLAG_TARGET_SPLIT_PROTECTED = "TARGET_SPLIT_PROTECTED"

SPHEREX_IMAGE_FLAG_BITS = {
    "TRANSIENT": 1 << 0,
    "OVERFLOW": 1 << 1,
    "SUR_ERROR": 1 << 2,
    "PHANTOM": 1 << 4,
    "REFERENCE": 1 << 5,
    "NONFUNC": 1 << 6,
    "DICHROIC": 1 << 7,
    "MISSING_DATA": 1 << 9,
    "HOT": 1 << 10,
    "COLD": 1 << 11,
    "FULLSAMPLE": 1 << 12,
    "SUR_MISMATCH": 1 << 13,
    "PHANMISS": 1 << 14,
    "NONLINEAR": 1 << 15,
    "VAR_UNDER": 1 << 16,
    "PERSIST": 1 << 17,
    "PERSIST_UNK": 1 << 18,
    "OUTLIER": 1 << 19,
    "CROSSTALK": 1 << 20,
    "SOURCE": 1 << 21,
    "GHOST": 1 << 22,
    "GHOST_EXT": 1 << 24,
    "BLOOM": 1 << 26,
    "SNOWBALL": 1 << 27,
    "HALO": 1 << 28,
    "SATELLITE_HALO": 1 << 29,
}
